server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basic_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true
    username: "${local.database.username}"
    password: "${local.database.password}"
    hikari:
      # 성능 최적화된 커넥션 풀 설정
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      # 추가 성능 설정
      connection-test-query: SELECT 1
      validation-timeout: 3000
      leak-detection-threshold: 60000
      pool-name: BasicProjectHikariPool

logging:
  level:
    com.basic.project: DEBUG
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.mybatis: DEBUG
    com.basic.project.mapper: DEBUG
    jdbc.sqltiming: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.connection: OFF

jwt:
  secret: "${local.jwt.secret}"
  expiration: 86400000  # 24시간 (밀리초)
  refresh-expiration: 604800000  # 7일 (밀리초)
  header: Authorization
  prefix: Bearer

# Spring Boot Actuator 설정 (개발 환경)
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 개발 환경에서는 모든 엔드포인트 노출
      base-path: /actuator
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: "GET,POST"
        allowed-headers: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    auditevents:
      enabled: true
    shutdown:
      enabled: false  # 보안상 비활성화
  info:
    env:
      enabled: true
    git:
      mode: full
    build:
      enabled: true
  metrics:
    tags:
      application: basic-project
      environment: local
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla:
        http.server.requests: 100ms, 500ms, 1s, 2s, 5s

# 애플리케이션 정보
app:
  name: 웹 프로젝트 기본 틀
  description: Spring Boot + React 기반 웹 애플리케이션
  version: 1.0.0
  environment: local